### PR TITLE
Set upper limit on NumPy version for compatibility with Numba

### PR DESCRIPTION
**Pull request by namurphy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is intended to address https://github.com/PlasmaPy/PlasmaPy/issues/1637.

### CODE REVIEW

**Comment by namurphy** [comment]
@conda-forge-admin, please rerender

**Comment by namurphy** [comment]
What I decided to try to do here is to add Numba to the list of requirements to build the package ("`host`"), even though Numba isn't actually required at that stage.  By adding this here, my intention is to make sure that the version of NumPy is chosen to be compatible with the version of Numba.  

An alternative would be to set an upper limit on the version of NumPy, which was my original intent.

**Review by rocco8773 — APPROVED** [review]

**Comment by namurphy** [comment]
@rocco8773 — thanks for the review!  Merging this now...and will test it shortly.

**Comment by namurphy** [comment]
I was starting to get frustrated that it conda-forge was taking so long to get updated, and then came here, and realized that I hadn't merged it yet.  If only I lived in a universe where there was a readily available meme of Captain Picard making a face palm.

**Pull request merged**
